#!/groovy

node('master') {
  stage('auto-build-master'){
    bat 'echo I am building master'
  }
  stage('build packages') {
    bat 'echo %PATH%'
  }
  stage('Deploy application') {
    bat 'echo deploying application'
  }
}
